# Site settings
title: "urbae"
description: "tentang kode-kodean , atau tema tema "
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://urbae.github.io"
author: "Uki"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics: UA-31452747-2 
disqus_shortname: urbae

plugins:
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-toc

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
